== Задание ==


=== Задача №1 ===

Компонент функциональности проверки доступности внешних ресурсов по протоколу HTTP делает запросы GET к ресурстам, url-адреса которых поступают на вход. Функциональность возращает список кодов статуса ответа в виде списка. Позиция кода ответа в этом списке соответствует позиции ресурса в списке на входе.

Пример:

Если на входе следующий список ресурсов 

[,go]
....
[]string{
    "http://some-resource-1.com", // Resource 1
    "http://some-resource-2.com", // Resource 2
    "http://some-resource-3.com", // Resource 3
}
....

и если `Resource 1` ответил c кодом статуса `200`, `Resource 2` ответил `301`, а `Resource 3` ответил `500`, то на выходе функции ожидается следующий список

[,go]
....
[]int{
    200,
    301,
    500,
}
....

==== Требуется: ====

1. Реализовать описанную функциональность в виде функции:
+
[,go]
....
func checkResources(resources []string) ([]int, error) { 
    // TODO
}
....
+
2. Обеспечить максимально быстрое выполнение запросов к ресурсам и обработку ответов от них.
3. Из внешних пакетов можно пользоваться только стандартной библиотекой языка.


=== Задача №2 ===

База данных PostgreSQL содержит информацию о пользвателях системы. Она хранит для каждого пользователя имя, возраст и email.

==== Требуется: ====

1. Написать SQL-запрос для создания таблицы `user` из описания задачи. Помимо указанной информации о пользователях в таблице также должен хранится целочисленный идентификатор пользователя, который может назначаться пользователю при его занесении в таблицу.

2. Для поиска пользователя по идентификатору обеспечить наличие соответствующего индекса.

3. Для поиска пользователя по имени обеспечить наличие соответствующего индекса.

4. Написать SQL-запрос для поиска пользователя по идентификатору `127`.

5. Написать SQL-запрос для поиска пользователей с именем `Ann`.

6. Написать SQL-запрос для поиска пользователей, чей возраст не менее `21` года.

7. В какой-то момент времени потребовалось также хранить информацию об адресе пользователя. Необходимо написать SQL-запрос на добавление поля `address` в таблицу `user`.